module.exports = {
  API_ID: process.env.API_ID,
  API_NAME: process.env.API_NAME,
  API_DISPLAY_NAME: process.env.API_DISPLAY_NAME,
  PORT: process.env.PORT || 8000,
  CLIENT_URL: process.env.CLIENT_URL,
  BASE_URL: process.env.BASE_URL,
  STORAGE_API_URL: process.env.STORAGE_API_URL,
  RP_ID: process.env.RP_ID,
  WEBAUTHN_ORIGIN: process.env.WEBAUTHN_ORIGIN,
  SESSION_SECRET: process.env.SESSION_SECRET,
  MAIL_HOST: process.env.MAIL_HOST,
  MAIL_PORT: process.env.MAIL_PORT,
  SPECTRA_EMAIL: process.env.SPECTRA_EMAIL,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  MAIL_PASSWORS: process.env.MAIL_PASSWORS,
  STORAGE_SESSION_SECRET: process.env.STORAGE_SESSION_SECRET,
};
